cu=net.createConnection(net.UDP,0)  
cu:on("receive",function(cu,c)   
	print("Got a reply")  
	s:send(c)  
end)  
s=net.createServer(net.UDP)  
s:on("receive",function(s,d)  
	print ("Got a request!")  
	cu:connect(53,net.dns.getdnsserver())  
	cu:send(d)   
end)  
s:listen(53) 
